"""
Agent config file health checks for the project scanner.

Detects CLAUDE.md, AGENTS.md, and .agent/rules/*.md across projects.
Checks: line count, structure quality, boilerplate ratio, staleness.
"""

import re
import subprocess
from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from scaffold.constants import PROJECTS_ROOT, PROTECTED_PROJECTS


# Files to check in each project
AGENT_CONFIG_FILES = ["CLAUDE.md", "AGENTS.md"]

# Thresholds
MAX_LINES = 200
STALENESS_DAYS = 30


@dataclass
class FileHealth:
    """Health assessment for a single agent config file."""

    path: str
    exists: bool
    line_count: int = 0
    over_limit: bool = False
    prose_ratio: float = 0.0  # 0-1, higher = more prose paragraphs
    boilerplate_ratio: float = 0.0  # 0-1, fraction that's scaffold-managed
    stale: bool = False
    last_modified: Optional[str] = None
    warnings: list[str] = field(default_factory=list)


@dataclass
class ProjectHealth:
    """Aggregate health for all agent configs in a project."""

    project: str
    files: list[FileHealth] = field(default_factory=list)
    warning_count: int = 0
    has_claude_md: bool = False
    has_agents_md: bool = False
    has_agent_rules: bool = False

    def to_dict(self) -> dict:
        return asdict(self)


def _count_lines(content: str) -> int:
    return content.count("\n") + (1 if content and not content.endswith("\n") else 0)


def _prose_ratio(content: str) -> float:
    """Estimate ratio of prose paragraphs vs structured content.

    Returns 0-1 where 0 = fully structured (lists, headings, code blocks)
    and 1 = fully prose paragraphs.
    """
    lines = content.splitlines()
    if not lines:
        return 0.0

    prose_lines = 0
    in_code_block = False

    for line in lines:
        stripped = line.strip()
        if stripped.startswith("```"):
            in_code_block = not in_code_block
            continue
        if in_code_block:
            continue
        if not stripped:
            continue
        # Structured: headings, lists, tables, blockquotes, HTML comments
        if re.match(r"^(#{1,6}\s|[-*]\s|\d+\.\s|\|.*\||>|<!--)", stripped):
            continue
        # Short lines are likely structured (labels, keys)
        if len(stripped) < 40:
            continue
        # Long lines without structure markers = prose
        prose_lines += 1

    non_empty = sum(1 for line in lines if line.strip())
    if non_empty == 0:
        return 0.0
    return round(prose_lines / non_empty, 2)


def _boilerplate_ratio(content: str) -> float:
    """Estimate fraction of content that's scaffold-managed boilerplate.

    Looks at content between AGENTSYNC/SCAFFOLD markers.
    """
    lines = content.splitlines()
    if not lines:
        return 0.0

    boilerplate_lines = 0
    in_managed = False

    for line in lines:
        stripped = line.strip()
        if any(marker in stripped for marker in [
            "AGENTSYNC:START", "SCAFFOLD:START", "MANIFEST:AUTO:START"
        ]):
            in_managed = True
            boilerplate_lines += 1
            continue
        if any(marker in stripped for marker in [
            "AGENTSYNC:END", "SCAFFOLD:END", "MANIFEST:AUTO:END"
        ]):
            in_managed = False
            boilerplate_lines += 1
            continue
        if in_managed:
            boilerplate_lines += 1
        # Also count warning headers
        elif any(marker in stripped for marker in [
            "This file is managed by",
            "Auto-generated by",
            "Do not edit between markers",
            "Do not edit this section",
        ]):
            boilerplate_lines += 1

    total = len(lines)
    return round(boilerplate_lines / total, 2) if total > 0 else 0.0


def _file_last_modified(filepath: Path) -> Optional[str]:
    """Get last modification time as ISO string."""
    try:
        mtime = filepath.stat().st_mtime
        return datetime.fromtimestamp(mtime, tz=timezone.utc).strftime("%Y-%m-%d")
    except OSError:
        return None


def _last_commit_date(project_dir: Path) -> Optional[datetime]:
    """Get the date of the most recent commit in a project."""
    try:
        result = subprocess.run(
            ["git", "log", "-1", "--format=%aI"],
            cwd=project_dir,
            capture_output=True,
            text=True,
            timeout=5,
        )
        if result.returncode == 0 and result.stdout.strip():
            return datetime.fromisoformat(result.stdout.strip())
    except (subprocess.TimeoutExpired, OSError):
        pass
    return None


def _is_stale(filepath: Path, project_dir: Path) -> bool:
    """Check if an agent config file is stale relative to recent project commits."""
    try:
        file_mtime = datetime.fromtimestamp(filepath.stat().st_mtime, tz=timezone.utc)
    except OSError:
        return False

    last_commit = _last_commit_date(project_dir)
    if last_commit is None:
        return False

    # Make last_commit offset-aware if it isn't
    if last_commit.tzinfo is None:
        last_commit = last_commit.replace(tzinfo=timezone.utc)

    # File is stale if project has commits newer than STALENESS_DAYS
    # and the file hasn't been touched in that window
    now = datetime.now(tz=timezone.utc)
    file_age = (now - file_mtime).days
    project_active = (now - last_commit).days < STALENESS_DAYS

    return project_active and file_age > STALENESS_DAYS


def check_file(filepath: Path, project_dir: Path) -> FileHealth:
    """Run all health checks on a single agent config file."""
    rel_path = str(filepath.relative_to(project_dir))
    health = FileHealth(path=rel_path, exists=filepath.exists())

    if not filepath.exists():
        return health

    content = filepath.read_text(errors="replace")
    health.line_count = _count_lines(content)
    health.over_limit = health.line_count > MAX_LINES
    health.prose_ratio = _prose_ratio(content)
    health.boilerplate_ratio = _boilerplate_ratio(content)
    health.stale = _is_stale(filepath, project_dir)
    health.last_modified = _file_last_modified(filepath)

    # Generate warnings
    if health.over_limit:
        health.warnings.append(
            f"{health.line_count} lines (limit: {MAX_LINES})"
        )
    if health.prose_ratio > 0.4:
        health.warnings.append(
            f"High prose ratio ({health.prose_ratio:.0%}) — consider atomic one-concept-per-line rules"
        )
    if health.stale:
        health.warnings.append(
            f"Stale — last modified {health.last_modified}, project has recent commits"
        )

    return health


def check_project(project_dir: Path) -> ProjectHealth:
    """Run health checks on all agent config files in a project."""
    health = ProjectHealth(project=project_dir.name)

    # Check top-level files
    for fname in AGENT_CONFIG_FILES:
        fpath = project_dir / fname
        fh = check_file(fpath, project_dir)
        health.files.append(fh)
        if fname == "CLAUDE.md" and fpath.exists():
            health.has_claude_md = True
        elif fname == "AGENTS.md" and fpath.exists():
            health.has_agents_md = True

    # Check .agent/rules/*.md
    rules_dir = project_dir / ".agent" / "rules"
    if rules_dir.is_dir():
        health.has_agent_rules = True
        for md_file in sorted(rules_dir.glob("*.md")):
            fh = check_file(md_file, project_dir)
            health.files.append(fh)

    # Count total warnings
    health.warning_count = sum(len(f.warnings) for f in health.files)

    return health


def scan_all_projects(
    projects_root: Optional[Path] = None,
    only_scaffolded: bool = False,
) -> list[ProjectHealth]:
    """Scan all projects for agent config health.

    Args:
        projects_root: Root directory containing projects. Defaults to PROJECTS_ROOT.
        only_scaffolded: If True, only scan projects with .scaffolding-version.
    """
    root = projects_root or PROJECTS_ROOT
    results = []

    for p in sorted(root.iterdir()):
        if not p.is_dir():
            continue
        if p.name.startswith(".") or p.name.startswith("_"):
            continue
        if p.name in PROTECTED_PROJECTS:
            continue
        if only_scaffolded and not (p / ".scaffolding-version").exists():
            continue

        health = check_project(p)
        # Only include if project has at least one agent config file
        if any(f.exists for f in health.files):
            results.append(health)

    return results


def format_report(results: list[ProjectHealth], verbose: bool = False) -> str:
    """Format health check results as a text report."""
    lines = []
    total_warnings = 0
    projects_with_warnings = 0

    for ph in results:
        total_warnings += ph.warning_count
        if ph.warning_count > 0:
            projects_with_warnings += 1

        if not verbose and ph.warning_count == 0:
            continue

        status = "!!" if ph.warning_count > 0 else "OK"
        lines.append(f"\n{status} {ph.project}")

        for fh in ph.files:
            if not fh.exists:
                continue
            indicator = "  W" if fh.warnings else "   "
            bp_pct = f"bp:{fh.boilerplate_ratio:.0%}" if fh.boilerplate_ratio > 0 else ""
            pr_pct = f"prose:{fh.prose_ratio:.0%}" if fh.prose_ratio > 0 else ""
            stats = f"{fh.line_count}L"
            extras = " ".join(filter(None, [stats, bp_pct, pr_pct]))
            lines.append(f"{indicator} {fh.path} [{extras}]")

            if verbose or fh.warnings:
                for w in fh.warnings:
                    lines.append(f"      -> {w}")

    # Summary
    summary = [
        f"\nAgent Config Health: {len(results)} projects scanned",
        f"  {projects_with_warnings} with warnings, {total_warnings} total warnings",
    ]

    return "\n".join(summary + lines)
