#!/usr/bin/env python3
"""
One-time cleanup of agentsync artifacts from scaffolded projects.
Card #5464.

Usage:
    uv run scripts/cleanup_agentsync.py                    # dry-run (default)
    uv run scripts/cleanup_agentsync.py --execute          # make changes
    uv run scripts/cleanup_agentsync.py --execute --commit # changes + commit
"""

import argparse
import re
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path

PROJECTS_ROOT = Path.home() / "projects"

# Marker patterns (prefix match — actual markers have trailing text)
SCAFFOLD_START = "<!-- SCAFFOLD:START"
SCAFFOLD_END = "<!-- SCAFFOLD:END"
AGENTSYNC_START = "<!-- AGENTSYNC:START"
AGENTSYNC_END = "<!-- AGENTSYNC:END"

# Comment lines injected by agentsync into CLAUDE.md
AGENTSYNC_COMMENT_PATTERNS = [
    re.compile(r"^\s*<!--\s*To modify synced rules:"),
    re.compile(r"^\s*<!--\s*uv run \$PROJECTS_ROOT/project-scaffolding/agentsync/"),
    re.compile(r"^\s*<!--\s*Source: \.agentsync/"),
]

# Projects to skip entirely (from scan_config.yaml ignore + protected)
SKIP_PROJECTS = {
    "project-scaffolding",  # already cleaned
    "_worktrees",
    "_tools",
    "__Knowledge",
    "openclaw",
    "nanoclaw",
    "fci-plugins",
    "github-repos",
}

# Special cases: protected projects that only need governance.md removed
GOVERNANCE_ONLY_PROJECTS = {"ai-journal", "writing"}


@dataclass
class Action:
    kind: str  # "trash", "strip", "skip", "empty_trash"
    path: Path
    detail: str = ""


@dataclass
class ProjectCleanup:
    name: str
    path: Path
    actions: list[Action] = field(default_factory=list)
    errors: list[str] = field(default_factory=list)


def discover_projects() -> list[Path]:
    """Find all project directories under PROJECTS_ROOT."""
    projects = []
    for child in sorted(PROJECTS_ROOT.iterdir()):
        if not child.is_dir():
            continue
        if child.name.startswith(".") or child.name in SKIP_PROJECTS:
            continue
        projects.append(child)
    return projects


def is_synced_governance(path: Path) -> bool:
    """Check if governance.md is a synced copy (has DO NOT EDIT header)."""
    try:
        content = path.read_text()
        return "DO NOT EDIT THIS FILE" in content[:500]
    except Exception:
        return False


def has_agentsync_markers(path: Path) -> bool:
    """Check if a file contains AGENTSYNC markers."""
    try:
        content = path.read_text()
        return AGENTSYNC_START in content
    except Exception:
        return False


def strip_markers(content: str, start_marker: str, end_marker: str) -> str:
    """Remove content between start and end markers (inclusive)."""
    lines = content.splitlines(keepends=True)
    result = []
    inside = False

    for line in lines:
        if start_marker in line:
            inside = True
            continue
        if end_marker in line:
            inside = False
            continue
        if inside:
            continue
        result.append(line)

    return "".join(result)


def strip_agentsync_comments(content: str) -> str:
    """Remove agentsync-injected comment lines from CLAUDE.md."""
    lines = content.splitlines(keepends=True)
    result = []
    for line in lines:
        if any(pat.match(line) for pat in AGENTSYNC_COMMENT_PATTERNS):
            continue
        result.append(line)
    return "".join(result)


def collapse_blank_lines(content: str) -> str:
    """Collapse runs of 3+ blank lines down to 2."""
    return re.sub(r"\n{4,}", "\n\n\n", content)


def is_effectively_empty(content: str) -> bool:
    """Check if content is empty or only whitespace/blank lines."""
    return not content.strip()


def scan_project(project: Path) -> ProjectCleanup:
    """Scan a project for agentsync artifacts and plan cleanup actions."""
    cleanup = ProjectCleanup(name=project.name, path=project)

    # Special case: governance-only projects
    if project.name in GOVERNANCE_ONLY_PROJECTS:
        gov = project / ".agent" / "rules" / "governance.md"
        if gov.exists() and is_synced_governance(gov):
            cleanup.actions.append(Action("trash", gov, "synced governance copy"))
        return cleanup

    # Check for scaffolding artifacts (only process scaffolded projects)
    sv = project / ".scaffolding-version"
    if not sv.exists():
        return cleanup  # not a scaffolded project

    # Phase 1: Pure deletions
    cleanup.actions.append(Action("trash", sv, "scaffolding metadata"))

    agentsync_dir = project / ".agentsync"
    if agentsync_dir.is_dir():
        file_count = sum(1 for _ in agentsync_dir.rglob("*") if _.is_file())
        cleanup.actions.append(Action("trash", agentsync_dir, f"directory ({file_count} files)"))

    gov = project / ".agent" / "rules" / "governance.md"
    if gov.exists() and is_synced_governance(gov):
        cleanup.actions.append(Action("trash", gov, "synced governance copy"))

    instructions = project / ".agent" / "rules" / "instructions.md"
    if instructions.exists() and has_agentsync_markers(instructions):
        cleanup.actions.append(Action("trash", instructions, "synced instructions copy"))

    # Trash .backup files in .agent/rules/
    agent_rules = project / ".agent" / "rules"
    if agent_rules.is_dir():
        for backup in agent_rules.glob("*.backup"):
            cleanup.actions.append(Action("trash", backup, "backup file"))

    # Phase 2: Marker stripping
    marker_files = {
        "CLAUDE.md": (AGENTSYNC_START, AGENTSYNC_END),
        "README.md": (SCAFFOLD_START, SCAFFOLD_END),
        "AGENTS.md": (SCAFFOLD_START, SCAFFOLD_END),
        "DECISIONS.md": (SCAFFOLD_START, SCAFFOLD_END),
        ".gitignore": (SCAFFOLD_START, SCAFFOLD_END),
    }

    for filename, (start, end) in marker_files.items():
        fpath = project / filename
        if not fpath.exists():
            continue

        content = fpath.read_text()
        if start not in content:
            continue

        # Strip markers
        stripped = strip_markers(content, start, end)

        # Extra cleanup for CLAUDE.md
        if filename == "CLAUDE.md":
            stripped = strip_agentsync_comments(stripped)

        stripped = collapse_blank_lines(stripped).strip() + "\n"

        if is_effectively_empty(stripped):
            cleanup.actions.append(Action("empty_trash", fpath, "empty after stripping markers"))
        else:
            original_lines = len(content.splitlines())
            new_lines = len(stripped.splitlines())
            removed = original_lines - new_lines
            cleanup.actions.append(Action(
                "strip", fpath,
                f"removed {removed} lines, kept {new_lines} lines"
            ))

    return cleanup


def trash_path(path: Path, dry_run: bool) -> bool:
    """Trash a file or directory. Returns True on success."""
    if dry_run:
        return True
    try:
        result = subprocess.run(
            ["trash", str(path)],
            capture_output=True, text=True, timeout=10,
        )
        return result.returncode == 0
    except Exception as e:
        print(f"  ERROR trashing {path}: {e}")
        return False


def execute_strip(path: Path, start_marker: str, end_marker: str, dry_run: bool) -> bool:
    """Strip markers from a file and write it back."""
    if dry_run:
        return True
    try:
        content = path.read_text()
        stripped = strip_markers(content, start_marker, end_marker)
        if path.name == "CLAUDE.md":
            stripped = strip_agentsync_comments(stripped)
        stripped = collapse_blank_lines(stripped).strip() + "\n"
        path.write_text(stripped)
        return True
    except Exception as e:
        print(f"  ERROR stripping {path}: {e}")
        return False


def is_git_clean(project: Path) -> bool:
    """Check if a project's git working tree is clean."""
    try:
        result = subprocess.run(
            ["git", "status", "--porcelain"],
            capture_output=True, text=True, timeout=10, cwd=project,
        )
        return result.returncode == 0 and not result.stdout.strip()
    except Exception:
        return False


def commit_project(project: Path, dry_run: bool) -> bool:
    """Stage all changes and commit in a project."""
    if dry_run:
        return True
    try:
        subprocess.run(["git", "add", "-A"], cwd=project, capture_output=True, timeout=10)
        result = subprocess.run(
            ["git", "commit", "-m",
             "chore: remove agentsync artifacts (#5464)\n\n"
             "The push-based sync system has been retired from project-scaffolding.\n"
             "Removed: .scaffolding-version, .agentsync/, synced governance/instructions, marker blocks.\n\n"
             "Co-Authored-By: Claude Opus 4.6 (1M context) <noreply@anthropic.com>"],
            cwd=project, capture_output=True, text=True, timeout=30,
        )
        return result.returncode == 0
    except Exception as e:
        print(f"  ERROR committing {project.name}: {e}")
        return False


def execute_cleanup(cleanup: ProjectCleanup, dry_run: bool, do_commit: bool) -> None:
    """Execute all planned actions for a project."""
    if not cleanup.actions:
        return

    # Track pre-existing dirty state
    was_clean = is_git_clean(cleanup.path)

    # Marker type lookup for strip actions
    marker_map = {
        "CLAUDE.md": (AGENTSYNC_START, AGENTSYNC_END),
        "README.md": (SCAFFOLD_START, SCAFFOLD_END),
        "AGENTS.md": (SCAFFOLD_START, SCAFFOLD_END),
        "DECISIONS.md": (SCAFFOLD_START, SCAFFOLD_END),
        ".gitignore": (SCAFFOLD_START, SCAFFOLD_END),
    }

    for action in cleanup.actions:
        if action.kind == "trash":
            trash_path(action.path, dry_run)
        elif action.kind == "empty_trash":
            trash_path(action.path, dry_run)
        elif action.kind == "strip":
            fname = action.path.name
            if fname in marker_map:
                start, end = marker_map[fname]
                execute_strip(action.path, start, end, dry_run)

    # Commit if requested
    if do_commit and not dry_run:
        if not was_clean:
            print(f"  SKIP COMMIT: {cleanup.name} had pre-existing uncommitted changes")
        else:
            if commit_project(cleanup.path, dry_run=False):
                print(f"  COMMITTED: {cleanup.name}")
            else:
                print(f"  COMMIT FAILED: {cleanup.name}")


def print_report(cleanups: list[ProjectCleanup], dry_run: bool) -> None:
    """Print a summary report."""
    mode = "DRY RUN" if dry_run else "EXECUTED"
    print(f"\n{'=' * 60}")
    print(f"  Agentsync Cleanup Report ({mode})")
    print(f"{'=' * 60}\n")

    total_trashed = 0
    total_stripped = 0
    total_projects = 0

    for c in cleanups:
        if not c.actions:
            continue
        total_projects += 1
        print(f"  {c.name}/")
        for a in c.actions:
            icon = {"trash": "TRASH", "empty_trash": "TRASH", "strip": "STRIP", "skip": "SKIP"}
            label = icon.get(a.kind, a.kind.upper())
            rel = a.path.relative_to(c.path)
            print(f"    {label}: {rel}  ({a.detail})")
            if a.kind in ("trash", "empty_trash"):
                total_trashed += 1
            elif a.kind == "strip":
                total_stripped += 1
        print()

    print(f"  Summary:")
    print(f"    {total_projects} projects affected")
    print(f"    {total_trashed} files/dirs trashed")
    print(f"    {total_stripped} files marker-stripped")
    print()


def main() -> None:
    parser = argparse.ArgumentParser(description="Clean up agentsync artifacts across all projects")
    parser.add_argument("--execute", action="store_true", help="Actually make changes (default is dry-run)")
    parser.add_argument("--commit", action="store_true", help="Commit changes in each project (requires --execute)")
    parser.add_argument("--project", "-p", help="Only clean a single project")
    args = parser.parse_args()

    dry_run = not args.execute
    do_commit = args.commit and args.execute

    if dry_run:
        print("\n  DRY RUN — no changes will be made. Pass --execute to apply.\n")

    # Discover and scan
    if args.project:
        target = PROJECTS_ROOT / args.project
        if not target.is_dir():
            print(f"Project not found: {target}")
            sys.exit(1)
        projects = [target]
    else:
        projects = discover_projects()

    cleanups = [scan_project(p) for p in projects]
    cleanups = [c for c in cleanups if c.actions]  # only projects with work

    # Report
    print_report(cleanups, dry_run)

    if not cleanups:
        print("  Nothing to clean up.")
        return

    # Execute
    for c in cleanups:
        execute_cleanup(c, dry_run, do_commit)

    if not dry_run:
        print_report(cleanups, dry_run=False)


if __name__ == "__main__":
    main()
